### ISSUE TITLE
hapus

### ISSUE THREAD

**Issue by quenieG** [quenieG/targetkinerja1#3]
header("Location: tw.php?id_triwulan=" . $id_tw); 
ade yg salah k dr alamat itok, soalnye dr yg ku pahamek dh batol tp tang an mengarah ke tabel tw kaknye an bite teapus.

<a href="hapus_tw.php?id_capaian=<?php echo $id_tw;?>" class="btn btn-danger btn-sm" onclick="return confirm('Anda yakin ingin menghapus data triwulan ini?')"><i class="fas fa-trash-alt"></i></a>

kaknye syntax iye awalnye pade bagian -> hapus_tw.php?id_capaian, awalnye kau gantinye jd hapus_tw.php?id_triwulan, nah pas iy an bise kaknye dh ku ganti k id capaian maok die kaknye jd an maok agk y ceritenye y gimn penasaran aku

**Comment by Vendot** [comment]
done

udah ku sesuaikan juak triwulan untok tiap prodi jdi di table capaian ku tambah id_prodi

**Comment by quenieG** [comment]
eror jadinye untok nambahkan data tw, kaknye ku liat erornye 
![image](https://github.com/quenieG/targetkinerja1/assets/128643714/72913a61-e74c-4113-bdf2-0df82562d48f)

eror iy menunjukkan buat form untok id prodi macam indikator k?
